name: Deploy PR preview

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR number'
        type: number
        required: true

concurrency: preview-${{ github.ref }}

env:
  PREVIEW_BASE_URL: https://preview-docs.voxel51.com

jobs:
  deploy-preview:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_publish.yml
    with:
      src-dir: site/
      dest-dir: pr-${{ inputs.pr-number }}
      secret-key: GCP_PREVIEW_DOCS_LOCATION
    secrets: inherit

  leave-pr-comment:
    needs: deploy-preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          number: ${{ inputs.pr-number }}
          message: |
            View preview at <br> ${{ env.PREVIEW_BASE_URL }}/pr-${{ inputs.pr-number }}/index.html <br>
