---
name: Publish Voxel51 Docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - CONTRIBUTING.md
      - GETTING_STARTED_FORMAT.md
      - LICENSE
      - README.md
      - .gitignore

jobs:
  publish-docs:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_publish.yml
    with:
      src-dir: site/
      secret-key: GCP_DOCS_LOCATION
    secrets: inherit
